enum MSG_CODES {
    // FRONT -> BACK
    CONNECT,
    DISCONNECT,
    SEND_QUEUED,
    SEND_BACK,
    BROADCAST_ALL_BACK,

        // BACK -> FRONT
    CONNECT_SUCCESS,
    CONNECT_FAILED,
    BROADCAST_MIRROR_FRONTS,
    BROADCAST_ALL_FRONTS,
    SEND_FRONT,
    SET_STATE,
    PATCH_STATE,
};

export default Protocol;
